[tool.black]
line-length = 100
target-version = ['py312']
preview = true

[tool.ruff]
line-length = 100
target-version = 'py312'

[tool.ruff.lint]
select = ["E", "F", "W", "B", "UP", "PT", "SIM", "PERF", "C", "I", "RUF"]
ignore = ["B905"]
